version: '3.8'

services:
  api-gateway:
    build: ./api-gateway-service
    ports:
      - "3000:3000"
    depends_on:
      - authentication
      - user-management
      - portfolio-service

  authentication:
    build: ./authentication-service
    ports:
      - "3001:3001"
    env_file:
      - ./authentication-service/.env
    depends_on:
      - auth-db
      - rabbitmq

  auth-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: stpt12
      POSTGRES_DB: auth_db
    ports:
      - "5434:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data

  user-management:
    build: ./user-management-service
    ports:
      - "3002:3002"
    env_file:
      - ./user-management-service/.env
    depends_on:
      - user-db
      - rabbitmq

  user-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: stpt12
      POSTGRES_DB: user_db
    ports:
      - "5433:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data

  portfolio-service:
    build: ./portfolio-management-service
    ports:
      - "3005:3005"  # Assuming portfolio service runs on port 3004
    depends_on:
      - portfolio-db

  portfolio-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: stpt12
      POSTGRES_DB: portfolio_db
    ports:
      - "5435:5432"
    volumes:
      - portfolio-db-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.9.17-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3003:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  auth-db-data:
  user-db-data:
  portfolio-db-data:
  prometheus_data:
  grafana_data:
