apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-management
  template:
    metadata:
      labels:
        app: portfolio-management
    spec:
      containers:
      - name: portfolio-management
        image: gcr.io/portfolio-tracker-427308/portfolio-service:latest
        ports:
        - containerPort: 3005
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 500m
