apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-db
  template:
    metadata:
      labels:
        app: portfolio-db
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_USER
          value: "postgres"  # Replace with your PostgreSQL username
        - name: POSTGRES_PASSWORD
          value: "stpt12"    # Replace with your PostgreSQL password
        - name: POSTGRES_DB
          value: "portfolio_db"  # Replace with your PostgreSQL database name
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-db
spec:
  selector:
    app: portfolio-db
  ports:
    - protocol: TCP
      port: 5432
