name: authentication-service pipeline

on:
  push:
    branches:
      - master
    paths:
      - 'authentication-service/**'
  pull_request:
    branches:
      - master
    paths:
      - 'authentication-service/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.17.1'

      - name: Install dependencies
        run: |
          cd authentication-service
          npm ci

      - name: Build and start
        run: |
          cd authentication-service
          npm run build --if-present


  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd authentication-service
          npm ci

      - name: SonarCloud Scan
        run: sonar-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

