name: portfolio management pipeline

on:
  push:
    branches:
      - master
    paths:
      - 'portfolio-management-service/**'
  pull_request:
    branches:
      - master
    paths:
      - 'portfolio-management-service/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.17.1'

      - name: Install dependencies
        run: |
          cd portfolio-management-service
          npm ci

      - name: Build and start
        run: |
          cd portfolio-management-service
          npm run build --if-present
